### ISSUE TITLE
Sayma v1.0 outstanding M-Labs items

### ISSUE THREAD

**Issue by jbqubit** [sinara-hw/sinara#501]
Moving M-Labs related items needed to get Sayma v1.0 running from #494. M-Labs has their own tracking for most of these but it helps me to see the full list. 

- [ ] RTM bitstream loading m-labs/artiq#813
- [x] DDR3 timing errors m-labs/misoc#75
- [x] MiSoC memory test failed m-labs/artiq#908
- [ ] Sayma serving as ARTIQ Master, communication via DRTIO
- [x] serwb working at 625 Mbps, unreliable at 1.25Gbps m-labs/artiq#856
- [ ] DRTIO over the RTM-AMC link

**Comment by hartytp** [comment]
This really doesn't belong here.
